domain: documentationacademy.org

image: prod-comms.ps5.docker-registry.canonical.com/documentationacademy.org

# Overrides for production
production:
  replicas: 3
  nginxConfigurationSnippet: |
    if ($host != 'documentationacademy.org' ) {
      rewrite ^ https://documentationacademy.org$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 1
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    if ($host != 'staging.documentationacademy.org' ) {
      rewrite ^ https://documentationacademy.org$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
